In [1]:
import numpy as np
oned_arrar = [1, 2, 3]
arrL = np.array(oned_arrar, dtype='int')
print(type(arrL))

<class 'numpy.ndarray'>


In [2]:
twoD_array = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(twoD_array, dtype='float32')
arr2

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [3]:
np.zeros(10, dtype="float32")


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [4]:
np.ones([3, 2], dtype="float")


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
np.full([3, 5], 33)


array([[33, 33, 33, 33, 33],
       [33, 33, 33, 33, 33],
       [33, 33, 33, 33, 33]])

In [6]:
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
# random 3*3 matrix
np.random.random((3, 3))

array([[0.31391062, 0.57720847, 0.83564021],
       [0.09867293, 0.45067856, 0.01044058],
       [0.55536331, 0.14204664, 0.72604358]])

In [8]:
# specifying the range
np.random.normal(0,2, [3,3]) #float data

array([[-3.46094369,  1.23996289,  1.19230878],
       [ 2.26759159,  0.17813407, -0.72453326],
       [ 0.38491022,  2.25135809,  3.57255436]])

In [9]:
np.random.randint(0,10, [3,3])


array([[7, 2, 0],
       [4, 9, 1],
       [5, 6, 7]])

In [10]:
sam_arr = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
print(f'The dimension of the arrary is {sam_arr.ndim}')

The dimension of the arrary is 3


In [11]:
sam_arr.dtype

dtype('int64')

In [12]:
arr = np.array([1,2,2])
arr

array([1, 2, 2])

In [13]:
arr = np.array([1,2,3, 'John'])
arr

array(['1', '2', '3', 'John'], dtype='<U21')

In [14]:
arr = np.array([1,2,3, 'John'], dtype=int)
arr

ValueError: invalid literal for int() with base 10: 'John'

In [15]:
arr = np.array([1,2,3, 'Josh'], dtype=str) #Upcast -> converting all dt into string

arr

array(['1', '2', '3', 'Josh'], dtype='<U4')

In [16]:
a = np.array([0,1,2,3,4])

print(f'1lst item: {a[0]}')
print(f'2nd item: {a[1]}')
print(f'3rd item: {a[2]}')
print(f'4th item: {a[3]}')
print(f'5th item: {a[4]}')

1lst item: 0
2nd item: 1
3rd item: 2
4th item: 3
5th item: 4


In [17]:
arr_2dim = np.array([
    [11, 12,13],
    [1,2,3],
    [6,7,8]
])
print(f'1lst item: {arr_2dim[0,0]}')
print(f'1lst item: {arr_2dim[0,1]}')
print(f'1lst item: {arr_2dim[0,2]}')
print(f'1lst item: {arr_2dim[1,0]}')
print(f'1lst item: {arr_2dim[1,1]}')
print(f'1lst item: {arr_2dim[1,2]}')
print(f'1lst item: {arr_2dim[2,0]}')

1lst item: 11
1lst item: 12
1lst item: 13
1lst item: 1
1lst item: 2
1lst item: 3
1lst item: 6


In [18]:
arr1 = np.array([2, 4, 5, 11, 7, 22, 12, 111, 52, 71, 21])
silce_arr1 = arr1[1:5]
print(silce_arr1)

[ 4  5 11  7]


In [19]:
# return every element step 2
arr1[::2]

array([ 2,  5,  7, 12, 52, 21])

In [20]:
# Reverse
arr1[::-1]

array([ 21,  71,  52, 111,  12,  22,   7,  11,   5,   4,   2])

In [21]:
arr2 =  np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# index 0, and prints from index 1
arr2[0, 1:]

array([2, 3])

In [22]:
base_arr = np.array([1,2,3,4,5,6])
print(base_arr)

[1 2 3 4 5 6]


In [23]:
copy_arr = base_arr.copy() #doesn't share same memory location


copy_arr
print(f'Do original array and copy array shares an memory? Ans: {np.shares_memory(base_arr, copy_arr)}')

Do original array and copy array shares an memory? Ans: False


In [24]:
copy_arr = base_arr   #same memory location share

print(f'Do original array and copy array shares an memory? Ans: {np.shares_memory(base_arr, copy_arr)}')

Do original array and copy array shares an memory? Ans: True
